# Generated by Django 4.1.2 on 2022-11-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
