# Generated by Django 4.1.2 on 2022-11-05 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('licenses', models.CharField(choices=[('dr', 'Doctor'), ('au', 'Authority')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('sys_number', models.IntegerField(blank=True, null=True, verbose_name='Med-System number')),
                ('slug', models.SlugField()),
                ('province', iranian_cities.fields.OstanField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('image', models.ImageField(null=True, upload_to='image/personal_image/', verbose_name='profile photo')),
                ('shift', models.CharField(choices=[('online', 'online'), ('phone', 'phone'), ('phone & online', 'phone & online')], max_length=20, verbose_name='taking turns online/phone')),
                ('sec_images', models.FileField(blank=True, null=True, upload_to='image/file/', verbose_name='additional files')),
                ('about', models.TextField(verbose_name='about me')),
                ('active', models.BooleanField(default=True, verbose_name='active user?')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'informations',
                'verbose_name_plural': 'informations',
            },
        ),
    ]
