# Generated by Django 4.1.2 on 2022-11-01 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/personal_image/', verbose_name='profile photo')),
                ('shift', models.CharField(blank=True, choices=[('online', 'online'), ('phone', 'phone'), ('phone & online', 'phone & online')], max_length=20, null=True, verbose_name='taking turns online/phone')),
                ('sec_images', models.FileField(blank=True, null=True, upload_to='image/file/', verbose_name='additional files')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about me')),
                ('active', models.BooleanField(default=True, verbose_name='active user?')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'informations',
                'verbose_name_plural': 'informations',
            },
        ),
    ]
