# Generated by Django 4.1.2 on 2022-11-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='licenses',
            field=models.CharField(choices=[('au', 'Authority'), ('dr', 'Doctor')], max_length=50),
        ),
    ]
