# Generated by Django 4.1.2 on 2022-11-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_licenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='licenses',
            field=models.CharField(choices=[('dr', 'Doctor'), ('au', 'Authority')], max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='doctors.doctor', verbose_name='user'),
        ),
    ]
