# Generated by Django 4.1.2 on 2022-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_licenses_alter_information_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='licenses',
            field=models.CharField(choices=[('au', 'Authority'), ('dr', 'Doctor')], max_length=50),
        ),
    ]
